name: youwell
description: Youth Wellness Hub - a private, supportive daily wellness companion.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.3
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  share_plus: ^13.3.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
