name: youwell
description: Youth Wellness Hub - a private, supportive daily wellness companion.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  supabase_flutter: ^2.17.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
